### ISSUE TITLE
ValueError: Arrays must be in chronological order to compute ACF

### ISSUE THREAD

**Issue by Foadsf** [bmorris3/interp-acf#3]
I have some data sets which are in chronological order but for some reason it returns this error only for one of them:

> Traceback (most recent call last):
  File "foo.py", line bar, in <module>
    lag, acf = interpolated_acf(dfs['strain'].values.astype(float), flux)
  File "path\to\Python37-32\lib\site-packages\interpacf-0.1-py3.7.egg\interpacf\interpacf.py", line 113, in interpolated_acf
ValueError: Arrays must be in chronological order to compute ACF

**Comment by bmorris3** [comment]
Try calling the `np.sort` function to ensure that it is sorted: 
```
lag, acf = interpolated_acf(np.sort(dfs['strain'].values.astype(float)), flux)
```

**Comment by Foadsf** [comment]
@bmorris3 I used a similar approach solving the problem using Pandas:
    `foo.sort_values(by=['bar'],inplace=True)`
although it was already sorted, as far as I could check, this solved the problem anyway. 

P.S. It would be great if there was a forum where I can post question, instead of opening issues. Unless you are ok with it?

**Comment by bmorris3** [comment]
This is an appropriate place to post issues 👍
